Feat - this adds basic support for packagist
ossf/package-feeds pull request #66
Opened 2021-02-27 21:47 UTC by phumberdroz

Hey,

Here is a very simple implementation for PHP feeds.

Couple of questions before I complete it:
- I would like to add tests and mock the http requests with: https://github.com/h2non/gock but did not wanna just include it. How do you feel about adding this kind of dependency?
- Currently dev updates are included and those are created when someone pushes a commit into a branch but does not add a tag. So there are versions like dev-<branch-name> (e.g. dev-master, dev-feat-packagist) should those be included? If not they can be easily filtered out.
- how should I document why I choose the api over the rss feed? (I did it because it is one endpoint for newly created packages and updates instead of 2 different rss feeds) 

closes #30

2021-02-27 22:06 UTC, jordan-wright commented
Hey @phumberdroz!

Thank you so much for sending this in- very exciting! Let me know when you're ready for a full review and I'll be happy to take a look.

> I would like to add tests and mock the http requests with: https://github.com/h2non/gock but did not wanna just include it. How do you feel about adding this kind of dependency?

I'd prefer to hold off on adding dependencies for testing unless they're critical. This particular case looks like a pretty straightforward case where you can use the `httptest` package to spin up a local server to send mocked out responses. You could just move the base URL out to a global unexported variable and then override that in your tests. Let me know if you'd like a more in-depth example!

> Currently dev updates are included and those are created when someone pushes a commit into a branch but does not add a tag. So there are versions like dev- (e.g. dev-master, dev-feat-packagist) should those be included? If not they can be easily filtered out.

I think we can start by including them and filter out if we find they're causing too much noise.

> how should I document why I choose the api over the rss feed? (I did it because it is one endpoint for newly created packages and updates instead of 2 different rss feeds)

I think documentation in general can be done using Go's standard documentation syntax. You can either include it in the documentation for your `Latest` function or, maybe better, add a `doc.go` that just includes the standard:

```go
// package packagist fetches packages from etc. etc
// more info here about how you picked your design
package packagist
```

2021-02-28 12:57 UTC, phumberdroz commented on feeds/packagist/packagist_test.go
> +		"/p2/nellyt/free-to-game-api-wrapper~dev.json": `{"packages":{"nellyt/free-to-game-api-wrapper":[{"name":"nellyt/free-to-game-api-wrapper","description":"Wrapper for API https://www.freetogame.com"
Let me know if I should exchange this with fake data.

2021-02-28 14:45 UTC, phumberdroz commented
I think this can be reviewed now.

2021-03-07 04:50 UTC, jordan-wright requested changes
This is looking great!

I've added some comments but they're mostly just stylistic. The approach looks just fine to me.

Thanks so much for sending this in!

2021-03-07 11:13 UTC, phumberdroz commented on feeds/packagist/packagist.go
> +	VersionHost = "https://repo.packagist.org"
I usually write test from the outside with `package packagist_test` which results in the test file only having access to exported functions/vars etc. 

I changed it. 👍

2021-03-21 03:09 UTC, jordan-wright requested changes
Apologies for the delay in getting back to you! This looks good. The only change I'd request is that we change `packagistversion.go` -> `version.go` and the current `version.go` -> `packagist.go` to match the other feeds.

When that's in good shape, feel free to tag me and I'll get this merged in. Thank you for all the great work here and for all your patience!

2021-03-23 09:57 UTC, phumberdroz commented
hey @jordan-wright,

I renamed the files as you requested.

And no worries this is an important effort which can help a lot of people to stay away from trouble.

2021-03-29 01:47 UTC, merged